### ISSUE TITLE
[CLI] Ability to provide multiple packages

### ISSUE THREAD

**Issue by jaudiger** [brioche-dev/brioche#75]
I was wondering if it would be possible to extend the current command line to set the parameter '-p, --project' multiple times:

```bash
> brioche install -p packages/openssl -p packages/rust
error: the argument '--project <PROJECT>' cannot be used multiple times
```

Installing more than one package at a time would be simplified, and prevent calling brioche more than needed. Few similar package managers allow this pattern, such as Nix:

```bash
> nix-shell -p oniguruma -p pssh
```

Progress:

- [ ] Build
- [x] Check
- [x] Format
- [x] Install
- [x] Publish
- [ ] Run sandbox
- [ ] Run

**Comment by kylewlacy** [comment]
Yep, I like this! I think the initial implementation could be as simple as looping over each `-p` argument and installing each one independently. The same should apply to the `-r` argument for installing packages from the registry (and it would make sense to me to allow mixing them together)

**Comment by jaudiger** [comment]
Ok, I'll work on this one if it suits you.

**Comment by jaudiger** [comment]
I updated the issue to add progress of the work done so far. The remained commands that have not been updated are:
- Build
- Run

Both commands are special, and should not been ported to use more than one project/registry project, I think.

What does it mean to run multiple projects at the same time? Should we run them sequentially, in parallel?
On the other side, the build command takes optionally an output parameter, but we can't use the same output path for multiple projects. We could have a sort of logic to append a path per project. But should we do open this use case? Let's say the command was: `brioche build -p packages/foo -p packages/bar -o output`. Brioche could end up with the following output folders:

- output/foo
- output/bar

**Comment by kylewlacy** [comment]
@jaudiger Agreed, I don't think either one should really be updated to take multiple arguments

Updating `brioche build` _might_ make sense, but I'd rather hold off until there's a concrete use-case for it
