### ISSUE TITLE
Add a recipe to glob a directory

### ISSUE THREAD

**Issue by kylewlacy** [brioche-dev/brioche#79]
The `Brioche.glob` function allows pulling in files into Brioche, grabbing a subset of inputs from the project directory. There is currently no way to do something similar for recipes themselves: you can get individual files from a directory recipe with the `.get()` method, but there is no way to get part of a directory. This also means there's no way to optionally get a file from a directory recipe: if the given path doesn't exist, `.get()` will fail

We should add a new recipe type called `glob`, which takes a directory recipe and a list of glob patterns as inputs, and bakes to a directory. This recipe will be exposed through a new `std.glob` function.

```typescript
const thing = std.directory({
  bin: std.directory({
    "foo": std.file("..."),
    "bar.sh": std.file("..."),
  }),
  lib: std.directory({
    "libbaz.so": std.file("..."),
  }),
});

return std.glob(thing, ["bin/**.sh", "lib/**/*"]);
// Bakes to a directory containing the following paths:
// - bin/bar.sh
// - lib/libbaz.so
```

**Comment by kylewlacy** [comment]
We could use this new recipe to clean up this hacky part of the Go package: https://github.com/brioche-dev/brioche-packages/blob/ce96562176d3664dfed6e292f608453492fa2806/packages/go/project.bri#L106-L114

**Comment by asheliahut** [comment]
This is needed for terraform package build. 
We need to update the go package to support globing directories for go.mod files.
